### ISSUE TITLE
`historyFor` emits warning message referring to `cols` paramenter

### ISSUE THREAD

**Issue by MattBrauer** [schardtbc/iexcloudR#4]
**What happens**
The iex API appears to now require a columns definition, manifested as a warning in use of functions that call it.

**How to reproduce**
After setting environment to define API keys, run following:

```
require(iexcloudR)
historyFor("AAPL")
```

**Expected behavior**
Printing of data frame containing stock price history for AAPL.

**Actual behavior**
Printing of stock history is followed by warning:
```
Warning message:
`cols` is now required.
Please use `cols = c(date, open, close, high, low, volume, uOpen, uClose, uHigh, 
    uLow, uVolume, change, changePercent, label, changeOverTime)` 
```

The parameter `cols` does not seem to be applicable to the `historyFor` function, however.

**Comment by schardtbc** [comment]
can you specify what version of R and dplyr you have installed?

**Comment by schardtbc** [comment]
interface to tidyr::unnest was changed, which leads to the displayed warning message. I will make an update to the package.

**Comment by schardtbc** [comment]
changed all calls to tidyr::unnest() to tidyr::unnest_legacy()
